// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNHqKC2d7A_d-BHoeoHoBaV6mrJ3O25I',
    appId: '1:702466027131:web:cafb44a92bef9503d6bcde',
    messagingSenderId: '702466027131',
    projectId: 'registra-3682e',
    authDomain: 'registra-3682e.firebaseapp.com',
    storageBucket: 'registra-3682e.firebasestorage.app',
    measurementId: 'G-DM3K3WPRJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-S4bv5lbryOX5UQzWJWOTFoQHr6wzTsM',
    appId: '1:702466027131:android:65182369b014e125d6bcde',
    messagingSenderId: '702466027131',
    projectId: 'registra-3682e',
    storageBucket: 'registra-3682e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMcwumGPdi4KDlDw1UYH-lp1i3oJhKf8',
    appId: '1:702466027131:ios:73b6e7edc334b91fd6bcde',
    messagingSenderId: '702466027131',
    projectId: 'registra-3682e',
    storageBucket: 'registra-3682e.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMcwumGPdi4KDlDw1UYH-lp1i3oJhKf8',
    appId: '1:702466027131:ios:73b6e7edc334b91fd6bcde',
    messagingSenderId: '702466027131',
    projectId: 'registra-3682e',
    storageBucket: 'registra-3682e.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNHqKC2d7A_d-BHoeoHoBaV6mrJ3O25I',
    appId: '1:702466027131:web:c51ca85121740d91d6bcde',
    messagingSenderId: '702466027131',
    projectId: 'registra-3682e',
    authDomain: 'registra-3682e.firebaseapp.com',
    storageBucket: 'registra-3682e.firebasestorage.app',
    measurementId: 'G-YPLLTLKNRX',
  );
}
